export const POPULAR_BRANDS = [
  'Acura', 'Alfa Romeo', 'Audi', 'BMW', 'BYD', 'Cadillac', 'Changan', 'Chevrolet',
  'Chery', 'Citroen', 'Daewoo', 'Daihatsu', 'Dodge', 'Fiat', 'Ford', 'Geely',
  'Genesis', 'GMC', 'Great Wall', 'Haval', 'Honda', 'Hyundai', 'Infiniti',
  'JAC', 'Jaguar', 'Jeep', 'Kia', 'Lada', 'Land Rover', 'Lexus', 'Mazda',
  'Mercedes-Benz', 'MINI', 'Mitsubishi', 'Nissan', 'Opel', 'Peugeot', 'Porsche',
  'RAM', 'Renault', 'Skoda', 'Smart', 'SsangYong', 'Subaru', 'Suzuki',
  'Tesla', 'Toyota', 'Volkswagen', 'Volvo', 'Vortex', 'Zotye',
  'Dongfeng', 'FAW', 'Foton', 'Lifan', 'Seat',
  'Lynk & Co', 'Zeekr', 'Nio', 'XPeng', 'Li Auto', 'Voyah',
  'Omoda', 'Jetour', 'Exeed', 'Aiways', 'Arcfox',
]

export const POPULAR_MODELS: Record<string, string[]> = {
  'Toyota': ['Camry', 'Corolla', 'RAV4', 'Land Cruiser', 'Highlander', 'Prius', 'Yaris', 'Hilux', 'Supra', 'C-HR', 'RAV4', 'Harrier', 'Alphard', 'Vellfire', 'bZ4X', 'Crown', 'Fortuner', 'Raize', 'Avensis', 'Verso'],
  'BMW': ['3 серия', '5 серия', '7 серия', 'X1', 'X3', 'X5', 'X7', '1 серия', '2 серия', '4 серия', '6 серия', 'X2', 'X4', 'X6', 'Z4', 'iX', 'i4', 'iX3', '4 серия Гран Купе', '2 серия Актив Турер'],
  'Mercedes-Benz': ['C-класс', 'E-класс', 'S-класс', 'GLC', 'GLE', 'A-класс', 'CLA', 'GLA', 'AMG GT', 'V-класс', 'GLB', 'EQS', 'EQE', 'EQA', 'EQB', 'GLS', 'CLS', 'CLE', 'W177', 'W206'],
  'Audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'e-tron', 'Q2', 'Q4 e-tron', 'RS3', 'RS6', 'RS7', 'S3', 'S4', 'S5'],
  'Volkswagen': ['Golf', 'Passat', 'Tiguan', 'Polo', 'Touareg', 'T-Roc', 'Arteon', 'ID.4', 'Teramont', 'Multivan', 'T-Cross', 'ID.3', 'ID.5', 'Taos', 'Caddy', 'Transporter', 'Amarok', 'Atlas', 'Polo Plus', 'Lamando'],
  'Hyundai': ['Solaris', 'Tucson', 'Santa Fe', 'Creta', 'Elantra', 'Sonata', 'ix35', 'Palisade', 'Custo', 'Staria', 'i30', 'Bayon', 'Kona', 'Ioniq 5', 'Ioniq 6', 'Accent', 'Venue', 'Grand Santa Fe', 'H-1', 'Santa Cruz'],
  'Kia': ['Rio', 'Sportage', 'Optima', 'Cerato', 'Sorento', 'Stinger', 'Ceed', 'Mohave', 'Carnival', 'Niro', 'EV6', 'Seltos', 'Sonet', 'Stonic', 'ProCeed', 'Ceed GT', 'K5', 'Morning', 'Ray', 'Soul'],
  'Nissan': ['Qashqai', 'X-Trail', 'Juke', 'Leaf', 'Almera', 'Teana', 'Patrol', 'Murano', 'Note', 'Sentra', 'Kicks', 'Ariya', 'Rogue', 'Pathfinder', 'Navara', '370Z', 'GT-R', 'Serena', 'Tiida', 'Versa'],
  'Mazda': ['CX-5', 'CX-3', 'CX-30', 'CX-9', 'CX-50', 'CX-60', '3', '6', '2', 'MX-5', 'CX-90', 'CX-80', 'MX-30', 'BT-50', 'RX-8', 'RX-7', 'MPV', 'CX-7', 'Demio', 'Premacy'],
  'Honda': ['Civic', 'CR-V', 'Accord', 'HR-V', 'Pilot', 'Jazz', 'Fit', 'Odyssey', 'Ridgeline', 'ZR-V', 'WR-V', 'City', 'Stepwgn', 'Vezel', 'Freed', 'N-Box', 'Life', 'Stream', 'Legend', 'S2000'],
  'Lexus': ['RX', 'NX', 'ES', 'LS', 'IS', 'UX', 'GX', 'LX', 'LC', 'RZ', 'TX', 'LM', 'LFA', 'CT', 'GS', 'SC', 'HS', 'RX L', 'NX L', 'ES L'],
  'Subaru': ['Forester', 'Outback', 'XV', 'Impreza', 'Legacy', 'WRX', 'Ascent', 'Solterra', 'BRZ', 'Levorg', 'Crosstrek', 'Tribeca', 'Baja', 'Justy', 'Dex', 'Stella', 'R1', 'R2', 'Trezeca', 'Exiga'],
  'Mitsubishi': ['Outlander', 'ASX', 'Pajero', 'Lancer', 'Eclipse Cross', 'Delica', 'Xpander', 'Montero Sport', 'Triton', 'i-MiEV', 'Pajero Sport', 'Outlander PHEV', 'L200', 'Colt', 'Galant', 'Carisma', 'Space Star', 'RVR', 'Eclipse', 'Montero'],
  'Geely': ['Coolray', 'Atlas Pro', 'Emgrand', 'Tugella', 'Azkarra', 'Monjaro', 'Geometry C', 'Okavango', 'Starray', 'Preface', 'Binrui', 'Boyu', 'Emgrand GT', 'KX11', 'Xingyue', 'Tianji', 'Icon', 'Haoyue', 'Galaxy L7', 'Galaxy L6'],
  'Chery': ['Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Tiggo 3', 'Omoda 5', 'Tiggo 7 Pro', 'Tiggo 8 Pro', 'eQ1', 'Fulwin 8', 'Tiggo 9', 'Omoda 9', 'Jetour Dashing', 'Jetour Traveller', 'Tiggo 4 Pro', 'Arrizo 8', 'eQ5', 'Tiggo 2', 'Arrizo 3', 'QQ'],
  'Haval': ['Jolion', 'F7', 'F7x', 'Dargo', 'H6', 'F5', 'M6', 'H9', 'P06', 'P07', 'Haval初恋', 'Haval Shenshou', 'Haval Xiaolong MAX', 'H2', 'H5', 'H6 Coupe', 'H8', 'Cool Dog', 'Chitu', 'Kuwait'],
  'Lada': ['Vesta', 'Granta', 'XRAY', 'Largus', 'Niva', 'Vesta Cross', 'Vesta SW', 'Granta Liftback', 'Niva Travel', 'Vesta SW Cross', 'XRAY Cross', 'Priora', 'Kalina', '2107', '2108', '2109', '2110', 'Samara', 'Oka', 'Taiga'],
  'Renault': ['Duster', 'Kaptur', 'Logan', 'Sandero', 'Koleos', 'Megane', 'Fluence', 'Captur', 'Kwid', 'Austral', 'Arkana', 'Scenic', 'Talisman', 'Kadjar', 'Symbol', 'Latitude', 'Twizy', 'Zoe', 'Clio', 'Master'],
  'Skoda': ['Octavia', 'Rapid', 'Karoq', 'Kodiaq', 'Superb', 'Fabia', 'Kamiq', 'Enyaq', 'Slavia', 'Kushaq', 'Kamiq', 'Scala', 'Roomster', 'Yeti', 'Praktik', 'Roomster', 'Citigo', 'Rapid Spaceback', 'Octavia Scout', 'Superb Combi'],
  'Ford': ['Focus', 'Escape', 'Explorer', 'Mustang', 'Edge', 'Kuga', 'Transit', 'F-150', 'Ranger', 'Puma', 'Mach-E', 'Bronco', 'Bronco Sport', 'Territory', 'Everest', 'Mondeo', 'Fiesta', 'EcoSport', 'S-Max', 'Galaxy'],
  'Chevrolet': ['Cruze', 'Tahoe', 'Traverse', 'Malibu', 'Camaro', 'Colorado', 'Equinox', 'Spark', 'Aveo', 'Captiva', 'Trailblazer', 'Suburban', 'Corvette', 'Trax', 'Bolt', 'Blazer', 'Silverado', 'Sonic', 'Orlando', 'Epica'],
  'SsangYong': ['Actyon', 'Rexton', 'Tivoli', 'Korando', 'Musso', 'Stavic', 'Torres', 'Rexton Sports', 'Korando e-Motion', 'Tivoli Grand', 'Kyron', 'Rodius', 'Chairman', 'Korando C', 'Actyon Sports', 'Rexton II', 'Rexton Sports Khan', 'Tivoli Air', 'Korando Turismo', 'New Actyon'],
  'Dongfeng': ['AX7', 'T5 EVO', 'Forthing T5', 'AEOLUS', 'Rich', 'Joyear', 'Fengon 500', 'Fengon 580', 'Fengon 700', 'Nammi 01'],
  'FAW': ['Besturn B70', 'Besturn X40', 'Besturn X80', 'Tianjin', 'Hongqi H5', 'Hongqi H9', 'Hongqi HS5', 'Hongqi HS7', 'Oley', 'Vita'],
  'Foton': ['Tunland', 'Sauvana', 'Toano', 'View', 'Aumark', 'Mars', 'BJ40', 'BJ60', 'BJ80', 'Gratour'],
  'Lifan': ['X60', 'X70', 'Myway', '330', '530', '620', '630', '820', 'Karsman', 'Solano'],
  'Seat': ['Leon', 'Ibiza', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Toledo', 'Exeo', 'Mii', 'Arosa'],
  'Tank': ['300', '400', '500', '700', '800'],
  'Omoda': ['5', '7', '9', 'C5', 'S5'],
  'Jetour': ['Dashing', 'Traveller', 'X70', 'X90', 'T2'],
  'Exeed': ['LX', 'TXL', 'VX', 'RX', 'SRT'],
  'Lynk & Co': ['01', '02', '03', '05', '06', '08', '09'],
  'Zeekr': ['001', '007', '009', 'X', 'Mix'],
  'Nio': ['ES6', 'ES8', 'EC6', 'ET5', 'ET7', 'ES7', 'EC7', 'ET9'],
  'XPeng': ['G3', 'G6', 'G9', 'P5', 'P7', 'X9', 'MONA M03'],
  'Li Auto': ['L6', 'L7', 'L8', 'L9', 'MEGA', 'One'],
  'Voyah': ['Free', 'Dreamer', 'Passion'],
  'Arcfox': ['Alpha S', 'Alpha T', 'Kaola'],
  'Aiways': ['U5', 'U7', 'U9'],
}
