export const POPULAR_BRANDS = [
  'Acura', 'Alfa Romeo', 'Audi', 'BMW', 'BYD', 'Cadillac', 'Changan', 'Chevrolet',
  'Chery', 'Citroen', 'Daewoo', 'Daihatsu', 'Dodge', 'Fiat', 'Ford', 'Geely',
  'Genesis', 'GMC', 'Great Wall', 'Haval', 'Honda', 'Hyundai', 'Infiniti',
  'JAC', 'Jaguar', 'Jeep', 'Kia', 'Lada', 'Land Rover', 'Lexus', 'Mazda',
  'Mercedes-Benz', 'MINI', 'Mitsubishi', 'Nissan', 'Opel', 'Peugeot', 'Porsche',
  'RAM', 'Renault', 'Skoda', 'Smart', 'SsangYong', 'Subaru', 'Suzuki',
  'Tesla', 'Toyota', 'Volkswagen', 'Volvo', 'Vortex', 'Zotye',
]

export const POPULAR_MODELS: Record<string, string[]> = {
  'Toyota': ['Camry', 'Corolla', 'RAV4', 'Land Cruiser', 'Highlander', 'Prius', 'Yaris', 'Hilux', 'Supra', 'C-HR'],
  'BMW': ['3 серия', '5 серия', '7 серия', 'X3', 'X5', 'X7', '1 серия', '2 серия', '4 серия', '6 серия'],
  'Mercedes-Benz': ['C-класс', 'E-класс', 'S-класс', 'GLC', 'GLE', 'A-класс', 'CLA', 'GLA', 'AMG GT', 'V-класс'],
  'Audi': ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'e-tron'],
  'Volkswagen': ['Golf', 'Passat', 'Tiguan', 'Polo', 'Touareg', 'T-Roc', 'Arteon', 'ID.4', 'Teramont', 'Multivan'],
  'Hyundai': ['Solaris', 'Tucson', 'Santa Fe', 'Creta', 'Elantra', 'Sonata', 'ix35', 'Palisade', 'Custo', 'Staria'],
  'Kia': ['Rio', 'Sportage', 'Optima', 'Cerato', 'Sorento', 'Sportage', 'Stinger', 'Ceed', 'M Mohave', 'Carnival'],
  'Nissan': ['Qashqai', 'X-Trail', 'Juke', 'Leaf', 'Almera', 'Teana', 'Patrol', 'Murano', 'Note', 'Sentra'],
  'Mazda': ['CX-5', 'CX-3', 'CX-30', 'CX-9', '3', '6', '2', 'MX-5', 'CX-60', 'CX-50'],
  'Honda': ['Civic', 'CR-V', 'Accord', 'HR-V', 'Pilot', 'Jazz', 'Fit', 'Odyssey', 'Ridgeline', 'ZR-V'],
  'Lexus': ['RX', 'NX', 'ES', 'LS', 'IS', 'UX', 'GX', 'LX', 'LC', 'RZ'],
  'Subaru': ['Forester', 'Outback', 'XV', 'Impreza', 'Legacy', 'WRX', 'Ascent', 'Solterra', 'BRZ', 'Levorg'],
  'Mitsubishi': ['Outlander', 'ASX', 'Pajero', 'Lancer', 'Eclipse Cross', 'Delica', 'Xpander', 'Montero Sport', 'Triton', 'i-MiEV'],
  'Geely': ['Coolray', 'Atlas Pro', 'Emgrand', 'Tugella', 'Azkarra', 'Monjaro', 'Geometry C', 'Okavango', 'Starray', 'Preface'],
  'Chery': ['Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Tiggo 3', 'Omoda 5', 'Tiggo 7 Pro', 'Tiggo 8 Pro', 'eQ1', 'Fulwin 8'],
  'Haval': ['Jolion', 'F7', 'F7x', 'Dargo', 'H6', 'F5', 'M6', 'H9', 'P06', 'P07'],
  'Lada': ['Vesta', 'Granta', 'XRAY', 'Largus', 'Niva', 'Vesta Cross', 'Vesta SW', 'Granta Liftback', 'Niva Travel', 'Vesta SW Cross'],
  'Renault': ['Duster', 'Kaptur', 'Logan', 'Sandero', 'Koleos', 'Megane', 'Fluence', 'Captur', 'Kwid', 'Austral'],
  'Skoda': ['Octavia', 'Rapid', 'Karoq', 'Kodiaq', 'Superb', 'Fabia', 'Kamiq', 'Enyaq', 'Slavia', 'Kushaq'],
  'Ford': ['Focus', 'Escape', 'Explorer', 'Mustang', 'Edge', 'Kuga', 'Transit', 'F-150', 'Ranger', 'Puma'],
  'Chevrolet': ['Cruze', 'Tahoe', 'Traverse', 'Malibu', 'Camaro', 'Colorado', 'Equinox', 'Spark', 'Aveo', 'Captiva'],
  'SsangYong': ['Actyon', 'Rexton', 'Tivoli', 'Korando', 'Musso', 'Stavic', 'Torres', 'Rexton Sports', 'Korando e-Motion', 'Tivoli Grand'],
}
